name: chord-visualizer-py310
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h38cb7af_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.2=h1ae2325_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=hcd7f573_2_cpython
  - readline=8.3=h46df422_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - cffi==2.0.0
      - flatbuffers==25.12.19
      - mediapipe==0.10.31
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pycparser==2.23
      - pyo==1.0.5
      - sounddevice==0.5.3
prefix: /opt/miniconda3/envs/chord-visualizer-py310
